# Generated by Django 5.0.3 on 2024-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
        ),
    ]
