# Generated by Django 5.0.3 on 2024-10-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateField(verbose_name='تاريخ بدء الايجار')),
                ('rent_end', models.DateField(verbose_name='تاريخ انتهاء الايجار')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الايجار')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي')], default='active', max_length=10, verbose_name='حالة الايجار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخر تعديل')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار')),
                ('tenants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'ايجار',
                'verbose_name_plural': 'الايجارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
