# Generated by Django 5.0.3 on 2024-10-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, help_text='مساحة العقار بالمتر المربع', max_digits=7)),
                ('rooms', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'متاح'), ('rented', 'مؤجر')], default='available', max_length=10)),
            ],
        ),
    ]
