# Generated by Django 5.0.3 on 2024-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العقار')),
                ('location', models.CharField(max_length=100, verbose_name='الموقع')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='مساحة العقار بالمتر المربع')),
                ('rooms', models.IntegerField(verbose_name='عدد الغرف')),
                ('property_type', models.CharField(choices=[('residential', 'سكني'), ('commercial', 'تجاري')], max_length=15, verbose_name='نوع العقار')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('rented', 'مؤجر')], default='available', max_length=10, verbose_name='الحالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة العقار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
