# Generated by Django 5.0.3 on 2024-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العقار')),
                ('address', models.CharField(max_length=300, verbose_name='عنوان العقار')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('shop', 'محل'), ('office', 'مكتب')], default='apartment', max_length=20, verbose_name='نوع العقار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='المساحة (م²)')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('rented', 'مؤجر'), ('maintenance', 'تحت الصيانة')], default='available', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='صورة العقار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
