# Generated by Django 5.0.3 on 2024-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('house', 'منزل'), ('office', 'مكتب'), ('land', 'أرض')], max_length=20, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('rented', 'مؤجر'), ('sold', 'مباع')], default='available', max_length=20, verbose_name='الحالة'),
        ),
    ]
